-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrTYKMNbcB5J9BLbr
bnnSGFGF4Moh8fcanQ9A6TWTVZ2gCgYIKoZIzj0DAQehRANCAAStFyiEur5JYFW6
doZUk2tZv372KXZ1UEBYBFeeJbLdEgrLNMB34tyymFslhwmsuxTMJ1Nb5atkxtoB
KFgQpuqe
-----END PRIVATE KEY-----