import fs from 'node:fs/promises';
import sharp from 'sharp';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { Pool } from 'pg';
const dir='.local/detail-orb',detail='.local/detail-experiment',bounded='.local/bounded-dino';
const read=async(p:string)=>JSON.parse(await fs.readFile(p,'utf8'));
const hash=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
const [oldRuns,oldSummary,runs,summary,orb,orbPolicy,job,firstPass,c2Stage1,prior,frozen,policy,manifest]=await Promise.all([
  read(`${detail}/runs.json`),read(`${detail}/summary.json`),read(`${dir}/c2-runs.json`),read(`${dir}/c2-summary.json`),
  read(`${dir}/orb-results.json`),read(`${dir}/orb-policy.json`),read(`${dir}/job.json`),read(`${dir}/fresh-first-pass.json`),
  read(`${dir}/c2-stage1.json`),read('.local/image-experiment/snapshot.json'),read(`${bounded}/frozen-selection.json`),
  read(`${detail}/policy.json`),read(`${bounded}/manifest.json`)]);
const notes:Record<number,string>={
  3032:'Full Black Widow card retained, tight projected face; binder pocket and adjacent cards removed.',
  3077:'Complete Captain America image/header/name retained. Thin green/table margin remains at left/bottom; usable isolation, not perfectly card-only.',
  3088:'Complete Random face and bottom logo retained; thin sleeve/edge margin and glare remain. No foil appearance is invented or transferred from the reference.',
  3093:'Complete Iceman artwork/title strip/logo retained. Some side/bottom background remains due reference extent/perspective mismatch; not perfectly card-only.',
  3095:'Automatic fallback: no sufficiently supported matching top10 reference; correct Vulture reference is outside pool at rank15.',
  3110:'Automatic fallback: projected reference boundary extends outside original. No unsafe clipping to force acceptance.',
  3113:'Complete Electro face and original white frame retained. Small surrounding paper/table margin remains, especially bottom; usable but not perfectly card-only.',
  3126:'Automatic fallback: true Phoenix reference is a graded slab and alternative same-art store photo has unverified inner boundary; no slab/scene extent projected.',
  3127:'Automatic fallback: projected full card extends beyond original bounds. Kept raw.',
};
const preservedReport=await fs.readFile('attached_assets/detail-reranker-report.html','utf8');
const preservedEvidence=preservedReport.match(/<script id="evidence" type="application\/json">([\s\S]*?)<\/script>/);
assert.ok(preservedEvidence,'Original A/B/C evidence report missing');
assert.deepEqual(oldRuns,JSON.parse(preservedEvidence[1]).runs,'Preserved A/B/C changed');
const visualQA=runs.map((r:any)=>({scanId:r.scanId,automaticAccepted:r.cropAccepted,
  visuallyUsable:r.cropAccepted,tightClean:r.scanId===3032,manualAcceptanceOverride:false,note:notes[r.scanId],
  warning:'Offline inspection assesses automatic outputs; it does not change the automatic crop/fallback choice used for C2.'}));
await fs.writeFile(`${dir}/visual-qa.json`,JSON.stringify(visualQA,null,2));
assert.equal(hash(await fs.readFile('.local/scan-review/decisions.json')),prior.decisionsHash);
assert.equal(hash(await fs.readFile('scripts/dev-detail-vision.ts')),policy.visionSourceHash);
assert.equal(hash(await fs.readFile('scripts/dev-orb-isolation.py')),orbPolicy.sourceHash);
assert.equal(hash(await fs.readFile(`${bounded}/frozen-selection.json`)),job.frozenSelectionHash);
for(const c of frozen.eligible){
  assert.equal(hash(await fs.readFile(`.local/scan-review/${c.originalPhotoFile}`)),c.imageHash);
  const first=firstPass.find((r:any)=>r.scanId===c.scanId),stage=c2Stage1.find((r:any)=>r.scanId===c.scanId),r=runs.find((r:any)=>r.scanId===c.scanId);
  assert.deepEqual(stage.top10.map((r:any)=>r.cardId).sort((a:number,b:number)=>a-b),r.top10.map((r:any)=>r.cardId).sort((a:number,b:number)=>a-b));
  if(!r.cropAccepted){assert.equal(stage.inputHash,c.imageHash);assert.deepEqual(first.vector,stage.vector);}
  const decision=orb.results.find((x:any)=>x.scanId===c.scanId);
  if(decision.selected)assert.ok(first.top10.some((x:any)=>x.cardId===decision.selected.cardId));
  if(decision.automaticAccepted){
    const match=decision.selected;
    assert.ok(match.inliers>=job.policy.minInliers&&match.inlierRatio>=job.policy.minInlierRatio&&match.referenceHullCoverage>=job.policy.minReferenceHullCoverage);
  }
}
if(process.env.NODE_ENV==='production')throw Error('DEV only');
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:1}),client=await pool.connect();
try{
  await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');
  const rows=(await client.query('SELECT key,reference_url AS url,embedding,content_digest FROM catalog_visual_references WHERE key=ANY($1::text[]) ORDER BY key',[prior.refs.map((r:any)=>r.key)])).rows;
  assert.equal(hash(JSON.stringify(rows)),prior.referencesHash);
  await client.query('COMMIT');
}finally{client.release();await pool.end();}
const integrity={same9:true,same1023Ids823Vectors:true,rawFirstPassTop10Identical:true,rerankerWeightsAndSourceUnchanged:true,originalsUnchanged:true,decisionsUnchanged:true,permanent958RowsUnchanged:true,referenceHash:prior.referencesHash,automaticDecisionsNotManuallyOverridden:true,rawFallbacks4:true,orbSourceHash:orbPolicy.sourceHash,
  originalABCRunsHash:hash(await fs.readFile(`${detail}/runs.json`)),c2CandidatePoolPrimary10:true};
await fs.writeFile(`${dir}/integrity.json`,JSON.stringify(integrity,null,2));
await fs.mkdir(`${dir}/cases`,{recursive:true});
for(const r of runs)await fs.writeFile(`${dir}/cases/${r.scanId}.json`,JSON.stringify({...r,automaticIsolation:orb.results.find((o:any)=>o.scanId===r.scanId),visualQA:visualQA.find((q:any)=>q.scanId===r.scanId)},null,2));
const esc=(x:any)=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const n=(x:number)=>x.toFixed(2);
const image=async(p:string)=>'data:image/jpeg;base64,'+(await sharp(await fs.readFile(p)).rotate().resize({width:190,height:250,fit:'inside'}).jpeg({quality:76}).toBuffer()).toString('base64');
const rate=(s:any)=>[s.top1,s.top3,s.top10].map(x=>`${x}/9 (${(100*x/9).toFixed(1)}%)`).join(' · ');
for(let offset=0;offset<runs.length;offset+=3){
  const tiles=[];
  for(const r of runs.slice(offset,offset+3)){
    const c=frozen.eligible.find((c:any)=>c.scanId===r.scanId);
    for(const [label,file] of [['Original',`.local/scan-review/${c.originalPhotoFile}`],['ORB automatic outline',`${dir}/${r.scanId}-orb-outline.jpg`],[r.cropAccepted?'Automatic crop':'RAW fallback',r.cropAccepted?`${dir}/${r.scanId}-orb-crop.jpg`:`.local/scan-review/${c.originalPhotoFile}`]]){
      const im=await sharp(await fs.readFile(file)).rotate().resize(220,290,{fit:'contain',background:'#ddd'}).jpeg().toBuffer();
      const text=Buffer.from(`<svg width="220" height="30"><rect width="220" height="30" fill="white"/><text x="4" y="20" font-size="12">${r.scanId} ${label}</text></svg>`);
      tiles.push(await sharp({create:{width:220,height:320,channels:3,background:'white'}}).composite([{input:im,left:0,top:0},{input:text,left:0,top:290}]).jpeg().toBuffer());
    }
  }
  await sharp({create:{width:660,height:960,channels:3,background:'white'}}).composite(tiles.map((input,i)=>({input,left:i%3*220,top:Math.floor(i/3)*320}))).jpeg({quality:92}).toFile(`${dir}/orb-contact-sheet-${offset/3+1}.jpg`);
}
const rows=[];
for(const r of runs){
  const c=frozen.eligible.find((c:any)=>c.scanId===r.scanId),old=oldRuns.find((x:any)=>x.scanId===r.scanId),detection=orb.results.find((x:any)=>x.scanId===r.scanId),p=manifest.positives.find((p:any)=>p.scanId===r.scanId);
  rows.push(`<tr><td><b>${r.scanId}</b><br>#${r.cardId} ${esc(p.name)}</td><td><img src="${await image(`.local/scan-review/${c.originalPhotoFile}`)}"></td><td><img src="${await image(`${dir}/${r.scanId}-orb-outline.jpg`)}"><br>${r.cropAccepted?'Automatic gate accepted':'Automatic gate failed → raw'}</td><td><img src="${await image(r.cropAccepted?`${dir}/${r.scanId}-orb-crop.jpg`:`.local/scan-review/${c.originalPhotoFile}`)}"><br><small>${esc(notes[r.scanId])}</small></td><td>${old.A.rank} / ${old.B.rank??'out10'} / ${old.C.rank??'out10'} / <b>${r.rank??'out10'}</b><br><small>C2 fresh-DINO rank ${r.stage1Rank}</small></td><td>#${r.top10[0].cardId} ${esc(r.top10[0].name)}<br><small>${n(r.timing.totalMs)}ms incl both DINO passes</small><details><summary>Top10 C2</summary><ol>${r.top10.map((x:any)=>`<li>#${x.cardId} ${esc(x.name)}<br>DINO ${x.similarity.toFixed(6)} / rerank ${x.rerankScore.toFixed(6)}<br>detail ${x.evidence.reliable?'enabled':'abstained'}</li>`).join('')}</ol></details><details><summary>Geometry evidence</summary>${detection.selected?`Selected reference #${detection.selected.cardId}; ${detection.selected.inliers} inliers; ratio ${n(detection.selected.inlierRatio)}; reference hull coverage ${n(detection.selected.referenceHullCoverage)}; median error ${n(detection.selected.medianReprojectionError)}px.`:'No candidate passed gates.'}<ul>${detection.candidates.map((x:any)=>`<li>#${x.cardId}: ${esc(x.accepted?'homography accepted':x.reason)}</li>`).join('')}</ul></details></td></tr>`);
}
const processOverhead=summary.orbProcessMs-summary.orbReferencePrecomputeMs-orb.results.reduce((s:number,r:any)=>s+r.guidedIsolationMs,0);
const evidence={oldSummary,oldRuns,c2Summary:summary,c2Runs:runs,orbPolicy,orbResults:orb,referenceBoundaryReview:orbPolicy.referenceBoundaryReview,visualQA,integrity,
  ordering:'Fresh raw DINO -> original top10 references -> ORB/RANSAC guided crop or exact raw fallback -> fresh canonical DINO -> unchanged top10 detail reranker.',
  dependency:'opencv-python-headless5.0.0.93 + numpy2.4.6 via package-management skill. No ML models or application imports. Python module already available.'};
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Exact-card reranker + candidate-guided ORB isolation</title><style>body{font:15px/1.5 system-ui;background:#f2f5fa;color:#182339;margin:0}main{max-width:1500px;margin:auto;padding:26px}h1{font-size:29px}h2{font-size:21px}.panel{padding:20px;margin:18px 0;background:white;border:1px solid #dce2ec;border-radius:12px}.metrics{display:flex;gap:12px;flex-wrap:wrap}.metrics>div{padding:14px;background:#eaf1fa;border-radius:8px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:10px;border-bottom:1px solid #dce2ec;text-align:left;vertical-align:top}th{background:#eaf0f8}td img{width:145px;height:190px;object-fit:contain;background:#ddd}small{color:#5f6c85}.scroll{overflow:auto}p{max-width:1100px}details{max-width:310px;margin-top:8px}ol{padding-left:18px}.warn{color:#a54c00}button{padding:10px 14px;background:#254470;color:white;border:0;border-radius:6px;margin-right:8px;cursor:pointer}code{overflow-wrap:anywhere}</style><main>
<h1>Candidate-guided ORB isolation: 5 usable crops, Random rank improves</h1><p>One additional, genuinely different development method · same9 confirmed cases · same frozen1023-ID TestB index · earlier A/B/C and reranker weights preserved.</p><button onclick="downloadJSON()">Download all evidence JSON</button><button onclick="downloadHTML()">Save self-contained report</button>
<section class="panel"><h2>Measured A / B / C / C2 comparison</h2><div class="metrics"><div><b>A · raw DINO</b><br>${rate(oldSummary.A)}</div><div><b>B · raw + reranker</b><br>${rate(oldSummary.B)}</div><div><b>C · earlier geometry + reranker</b><br>${rate(oldSummary.C)}</div><div><b>C2 · ORB-guided crop + reranker</b><br>${rate(summary)}</div></div><p>Each line reports Top1 / Top3 / Top10. <b>C2 Top1 stays7/9, Top3 improves7/9→8/9.</b> Black Widow remains correct; Iceman remains correct. Random Gold improves rank4→2 but Rainbow still wins. Vulture remains stage1 rank15 and absent from top10; neither guided isolation nor reranking can recover a reference outside their pool.</p>
<p>Automatic homography gates accepted <b>5/9</b> (55.6%); independent visual inspection found all5 retain the complete target card and are usable. <b>No automatic decision was changed by offline visual QA.</b> Four of the five retain some sleeve/table/background margins; only Black Widow is a tight clean-face crop. Therefore5/9 is usable isolation, <b>not five perfectly card-only outputs</b>. No clipped artwork/internal-art quadrilateral like the prior Hough failures was accepted.</p></section>
<section class="panel"><h2>Different method, same image-only boundaries</h2><p>Order: <b>fresh raw DINO → raw top10 candidates → ORB binary features and RANSAC homography → project the verified reference card boundary into the query → crop or raw fallback → fresh DINO → unchanged detail reranker</b>. Both DINO passes count toward timing. Candidate selection for homography uses geometric support only, never the correct label, card metadata or DINO similarity score.</p>
<p>ORB uses3000 features, Lowe ratio0.75, unique target matches and RANSAC3px. Gates require≥20 inliers, inlier ratio≥0.50, reference convex-hull coverage≥25%, inlier span≥50% in both axes, median reprojection≤3px and95th-percentile≤6px, convex in-bounds projected corners, query area15–90%, and bounded perspective/shape. Competing high-support candidates projecting different rectangles trigger ambiguity fallback. Parameters were fixed for this one method; no score-based retuning.</p>
<p><b>Reference physical boundary is a prerequisite.</b> All63 unique raw-top10 reference images were independently inspected for their extent before matching. Only34 tightly framed complete card faces were enabled for boundary projection. Slabs, photographed scenes, large margins, store panels and uncertain watermark/framing were disabled; the outer photo extent was not blindly treated as a card rectangle. This is offline reference-image preparation, <b>not an automatic general catalog-boundary solution</b>. No per-query corners or correct-label-selected reference was supplied. Query crops inherit only geometric coordinates/aspect; reference colors/artwork are never pasted into the query.</p>
<p>OpenCV headless supplies standard ORB/RANSAC; NumPy is its numerical dependency. Package-management skill installed <code>opencv-python-headless5.0.0.93</code> and <code>numpy2.4.6</code> in its managed Python environment. No GUI packages, large ML models, paid APIs, production imports or model changes were added. The generated placeholder Python app was removed.</p></section>
<section class="panel"><h2>Actual automatic outputs and per-case ranks</h2><p>Ranks column is A / B / original C / C2. Four failed gates preserve the exact original query bytes; all9 remain in scoring. Grey output bars are uniform2:3 padding, not stretched artwork.</p><div class="scroll"><table><tr><th>Case</th><th>Original</th><th>Automatic projected boundary</th><th>C2 actual input / visual QA</th><th>A / B / C / C2 rank</th><th>C2 result / evidence</th></tr>${rows.join('')}</table></div></section>
<section class="panel"><h2>Known cases and remaining constraints</h2><ul><li><b>Black Widow3032:</b> raw DINO2, original reranker1, C2 DINO1 and final1.507 ORB inliers; tight card isolation removes binder contamination.</li><li><b>Random3088:</b> correct Gold selected as the strongest geometric reference (not by label);355 inliers. Fresh crop DINO puts Silver1, Rainbow2, Gold3; unchanged reranker yields Rainbow1, Gold2, Silver3. Geometry improves locality but does not prove finish identity. Gold/Rainbow detail alignment still abstains; Silver's detail score falls. No claim that Gold is now solved.</li><li><b>Iceman3093:</b>328 inliers; original DINO2 becomes crop DINO1 and final1. Some edge/background margin remains.</li><li><b>Vulture3095:</b> correct reference never reaches raw top10, so no matching geometry and no stage2 recovery. Primary top10 was not silently enlarged.</li><li><b>Magneto3110 and Phoenix3127:</b> projected full boundaries extend outside original; fail safely rather than clipping corners to force acceptance.</li><li><b>Phoenix3126:</b> trusted inner boundary unavailable in graded-slab/store images; raw fallback despite correct DINO#1. Semantic upright follows reference geometry where usable, but is not universally established for arbitrary references.</li></ul><p>Reference-guided ORB meaningfully improves usable isolation from1/9 to5/9 here. It still depends on suitable top10 reference coverage and texture, does not guarantee zero background or handle all glare/sleeves, and has no independent held-out validation. Keep the existing manual-crop fallback and explicit collector confirmation. Stop this bounded method iteration here rather than tune nine cases.</p></section>
<section class="panel"><h2>Timing — both DINO passes included</h2><table><tr><th>Operation</th><th>Measured milliseconds</th></tr><tr><td>First raw DINO call including cold model load</td><td>${n(summary.firstColdDinoMs)}</td></tr><tr><td>Mean first-pass DINO, including one cold call</td><td>${n(summary.meanTiming.firstDinoMs)}</td></tr><tr><td>Mean guided query ORB/matching/gates/warp/write</td><td>${n(summary.meanTiming.guidedIsolationMs)}</td></tr><tr><td>Mean second fresh DINO</td><td>${n(summary.meanTiming.secondDinoMs)}</td></tr><tr><td>Mean first / second exact search</td><td>${n(summary.meanTiming.firstSearchMs)} / ${n(summary.meanTiming.secondSearchMs)}</td></tr><tr><td>Mean query features / unchanged rerank</td><td>${n(summary.meanTiming.queryFeatureMs)} / ${n(summary.meanTiming.rerankMs)}</td></tr><tr><td>Mean C2 total, both passes including cold first</td><td>${n(summary.meanTiming.totalMs)}</td></tr><tr><td>Warm batch-path mean (remaining8 queries)</td><td>${n(summary.warmMeanTotalMs)}</td></tr><tr><td>One-time ORB reference preparation,34 references</td><td>${n(summary.orbReferencePrecomputeMs)}</td></tr><tr><td>Additional detail-reference feature preparation</td><td>${n(summary.additionalReferenceFeatureComputeMs)}</td></tr><tr><td>Python batch process elapsed / residual startup and I/O beyond measured reference/query stages</td><td>${n(summary.orbProcessMs)} / ${n(processOverhead)}</td></tr></table>
<p>Eight warm query paths finish under1second; cold first total is${n(runs[0].timing.totalMs)}ms. Reference ORB/detail feature preparation and Python batch startup are separated, not hidden inside “warm” totals. This script caches ORB reference descriptors in one batch process; it is not a deployed persistent service. Download/DB/original file I/O and offline reference verification are outside query timings. Guided-isolation timings include crop/outline encoding and writes. Human visual QA is not claimed as instant production work. These measurements support a practical warm visual path, not an autonomous production SLA.</p></section>
<section class="panel"><h2>Integrity and conclusion</h2><p>Fresh raw first-pass top10s exactly match the preserved prior run. Reranker source and weights unchanged. Stage2 stays within its fresh C2 top10. All9 original hashes/manual decisions unchanged;4 fallback query byte hashes and fresh vectors exactly match their raw originals. All original958 permanent reference rows were verified again by a read-only DEV transaction: <code>${prior.referencesHash}</code>. The1023-ID/823-vector frozen hard-negative index is unchanged. Automatic crop outcomes are distinct from offline visual inspection and were never manually overridden.</p>
<p><b>Continue development of candidate-guided isolation plus exact-card reranking, not automatic collection decisions.</b> Top1 remains7/9, Top3 rises8/9; Random's exact Gold/Rainbow finish remains unresolved and Vulture needs stage1 recall improvement. Five usable crops are stronger evidence than the unsafe Hough proposals, but reference-boundary curation and residual margins remain real constraints. No further method tuning was performed after this run.</p><p>No production access, publishing, full/permanent indexing, schema/catalog/label/image changes, Cloudinary writes, collections/ownership changes or app/UI/manual-crop changes. Full indexing remains paused. Only isolated experiment scripts, artifacts and the authorized headless-CV dependency setup were added.</p></section>
<script id="evidence" type="application/json">${JSON.stringify(evidence).replace(/</g,'\\u003c')}</script><script>function saveBlob(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function downloadJSON(){saveBlob(new Blob([JSON.stringify(JSON.parse(document.getElementById('evidence').textContent),null,2)],{type:'application/json'}),'detail-orb-results.json')}function downloadHTML(){saveBlob(new Blob(['<!doctype html>'+document.documentElement.outerHTML],{type:'text/html'}),'detail-reranker-orb-report.html')}</script></main></html>`;
await fs.writeFile('attached_assets/detail-reranker-orb-report.html',html);
console.log('REPORT attached_assets/detail-reranker-orb-report.html',Buffer.byteLength(html),'bytes',integrity);