import { Resend } from 'resend';
import { db } from '../db';
import { emailLogs, users } from '../../shared/schema';
import { eq } from 'drizzle-orm';
import { passwordResetTemplate } from './emailTemplates';

const DEFAULT_FROM = 'Marvelous Card Vault <no-reply@marvelcardvault.com>';

// ============================================================
// Resend client — primary provider for ALL app email.
// Lazily initialized so a missing RESEND_API_KEY never crashes
// unrelated app functionality at startup.
// ============================================================

let resendClient: Resend | null = null;

function getResendClient(): Resend {
  if (!process.env.RESEND_API_KEY) {
    throw new Error(
      'RESEND_API_KEY is not configured. Add it to Replit Secrets to enable email sending.'
    );
  }
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

async function logEmailToDb(
  to: string,
  subject: string,
  template: string,
  jobName?: string
): Promise<void> {
  try {
    let userId: number | null = null;
    try {
      const user = await db.select({ id: users.id })
        .from(users)
        .where(eq(users.email, to))
        .limit(1);
      userId = user[0]?.id || null;
    } catch (error) {
      console.warn(`Could not find userId for email ${to}`);
    }

    await db.insert(emailLogs).values({
      userId,
      email: to,
      template,
      subject,
      jobName: jobName || null,
    });
  } catch (error) {
    console.warn(`Could not write email_logs entry for ${to}:`, error);
  }
}

export interface SendEmailOptions {
  to: string;
  subject: string;
  html: string;
  template?: string;
  jobName?: string;
}

export interface ResendEmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
  from?: string;
  replyTo?: string;
  template?: string;
  jobName?: string;
}

/**
 * Centralized email sending via Resend — primary provider for all app email.
 * Preserves the original sendEmail(to, subject, html, template, jobName) signature
 * so all existing callers (emailTriggers.ts etc.) work without changes.
 *
 * Logs every send to the email_logs table.
 * Throws a clear error if RESEND_API_KEY is missing — callers handle it.
 */
export async function sendEmail(
  to: string,
  subject: string,
  html: string,
  template: string = 'unknown',
  jobName?: string
): Promise<void> {
  await sendResendEmail({ to, subject, html, template, jobName });
}

/**
 * Low-level Resend send — accepts full options including text, from, replyTo.
 * Called by sendEmail (above) and directly by routes that need those extra fields.
 */
export async function sendResendEmail(options: ResendEmailOptions): Promise<string | undefined> {
  const {
    to,
    subject,
    html,
    text,
    from = DEFAULT_FROM,
    replyTo,
    template = 'unknown',
    jobName,
  } = options;

  let client: Resend;
  try {
    client = getResendClient();
  } catch (error) {
    console.error(`❌ [Resend] Cannot send email to ${to} | Template: ${template} | ${error instanceof Error ? error.message : error}`);
    throw error;
  }

  try {
    const { data, error } = await client.emails.send({
      from,
      to,
      subject,
      html,
      ...(text ? { text } : {}),
      ...(replyTo ? { replyTo } : {}),
    });

    if (error) {
      throw new Error(`Resend API error: ${error.name || 'unknown'} — ${error.message || JSON.stringify(error)}`);
    }

    await logEmailToDb(to, subject, template, jobName);
    console.log(`✅ [Resend] Email sent to ${to} | Template: ${template} | Job: ${jobName || 'immediate'} | Message ID: ${data?.id}`);
    return data?.id;
  } catch (error) {
    console.error(`❌ [Resend] Error sending email to ${to} | Template: ${template}:`, error);
    throw error;
  }
}

/**
 * Send a branded password reset email via Resend.
 * The reset link is generated by Firebase Auth (token/expiry fully handled by Firebase).
 */
export async function sendPasswordResetEmail(params: {
  to: string;
  resetUrl: string;
  userName?: string;
}): Promise<void> {
  const { to, resetUrl } = params;
  const html = passwordResetTemplate({ email: to }, resetUrl);
  await sendResendEmail({
    to,
    subject: 'Reset Your Password',
    html,
    template: 'password-reset',
  });
}
